language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
  - ./vendor/bin/phpunit
  - php coverage-checker.php build/logs/clover.xml 1
  - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 ./src/); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
